### ISSUE TITLE
Log list from Google returns 404 

### ISSUE THREAD

**Issue by pdeardorff-r7** [GovAuCSU/ctlog-acquisition#10]
The JSON log list now returns a 404.  

https://github.com/GovAuCSU/ctlog-acquisition/blob/master/ctlist.go#L29

It looks like the new list uses a versioned endpoint: 

https://www.gstatic.com/ct/log_list/v3/log_list.json

**Comment by bladeswords** [comment]
Thanks for the report @pdeardorff-r7!  Just pushed f6a04a7ad8b5e8c6580b74b6a36ac7d8484d3d43 .

This should now use the updated endpoint.

**Comment by bladeswords** [comment]
Please let me know if you have any issues :)

**Comment by pdeardorff-r7** [comment]
Thanks @bladeswords I believe the schema changed in the JSON so the code will have to loop through the `operators` keys and then `logs`.  I'm fairly new to Go so haven't been able to implement it myself.  

https://github.com/GovAuCSU/ctlog-acquisition/blob/0abe54a32296ea8c328991899245e7d3796f4629/cmd/main.go#L183

**Comment by pdeardorff-r7** [comment]
@bladeswords I'm going to give the fix a try and open a PR.
