### ISSUE TITLE
Does not close file handles properly

### ISSUE THREAD

**Issue by bladeswords** [GovAuCSU/ctlog-acquisition#9]
After running for a long period of time, it appears to have too many open file handles.

```2019/03/17 18:08:21 [ERROR] Fail to open file static/ct_log_2019.03.17_10.08.21.txt. Error: open static/ct_log_2019.03.17_10.08.21.txt: too many open files
2019/03/17 18:13:21 [INFO] Preparing our output file: static/ct_log_2019.03.17_10.13.21.txt
2019/03/17 18:13:21 [ERROR] Fail to open file static/ct_log_2019.03.17_10.13.21.txt. Error: open static/ct_log_2019.03.17_10.13.21.txt: too many open files
```

**Comment by tsellers-r7** [comment]
Out of curiosity, how many cores is this running on?  I assume the code doesn't emit `[ERROR] Error while changing max open file descriptors` when starting, correct?

I ran into this in the past as well and tried to fix it here:
https://github.com/GovAuCSU/ctlog-acquisition/blob/master/cmd/main.go#L267-L274

Given the functionality of the code it made sense but based on your report it would seem like something is leaking them.

**Comment by tsellers-r7** [comment]
I've taken cursory look as I don't have time at to moment to dive in and test. It looks like we're opening the output files in `RealGetLogToFile` and not closing them.

https://github.com/GovAuCSU/ctlog-acquisition/blob/master/cmd/main.go#L164

**Comment by bladeswords** [comment]
This is just running on a random (cheap) VPS with 8 cores allocated to it.  There was no error relating to changing max file descriptors when starting it either - correct.

For context it was run using - `./ct-log -disable-webserver -start-current`
I have previous run this, when outputting to a single file - which ran for a couple of weeks before the VPS died (as I said...cheap provider)

Thanks for taking a look, I am too am short of time and haven't looked at it at all (and suck at Go)

**Comment by bladeswords** [comment]
Pretty sure a f.Close() would help/resolve.  Probably after https://github.com/GovAuCSU/ctlog-acquisition/blob/master/cmd/main.go#L186

Will give it a crack in the docker container soon

**Comment by bladeswords** [comment]
Revised the previous commit to reflect a suggestion by @santrancisco 

Also the docker container has been running for almost 24 hours with no issue...will keep it going for a while longer yet before closing off this issue

**Comment by bladeswords** [comment]
Ran for several weeks without issue.  Closing.
